name: main.yml

on :
  push:
  
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        
        - name: Print message
          run: echo "Workflow triggered"

      
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Run the code
          run: |
            make run
      
