name: main.yml

on :
  push:
  
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout code
          uses: actions/checkout@v2
        
        - name: Print message
          run: echo "Workflow triggered"

        - name: Install dependencies
          run: |
            make install

        - name: Build code
          run: |
            make run
  
