name: main.yml

on :
  push:
  
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: login Dockerhub
          uses: docker/login-action@v1
          with: 
            username: musawhyne
            password: aezakmi619f8f89

        - name: docker build
          run: docker build -t musawhyne/test:ver .

        - name: docker img push
          run: docker push musawhyne/test:ver